// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ZVERMrGNkAAo1jeYsHamd0esOJv0nKU',
    appId: '1:271054827387:web:a068bc995727e198fc57de',
    messagingSenderId: '271054827387',
    projectId: 'banalyze-d42d9',
    authDomain: 'banalyze-d42d9.firebaseapp.com',
    storageBucket: 'banalyze-d42d9.firebasestorage.app',
    measurementId: 'G-34XPPFJG82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QuPNR864fTNukUvd302WBwrFwMKx_Fk',
    appId: '1:271054827387:android:abb6c4d963158db6fc57de',
    messagingSenderId: '271054827387',
    projectId: 'banalyze-d42d9',
    storageBucket: 'banalyze-d42d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSPm_XhUF7dr_pVJvRD57eKrlk9YLHcI',
    appId: '1:271054827387:ios:c2be63d766a415c6fc57de',
    messagingSenderId: '271054827387',
    projectId: 'banalyze-d42d9',
    storageBucket: 'banalyze-d42d9.firebasestorage.app',
    iosBundleId: 'com.example.banalyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSPm_XhUF7dr_pVJvRD57eKrlk9YLHcI',
    appId: '1:271054827387:ios:c2be63d766a415c6fc57de',
    messagingSenderId: '271054827387',
    projectId: 'banalyze-d42d9',
    storageBucket: 'banalyze-d42d9.firebasestorage.app',
    iosBundleId: 'com.example.banalyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ZVERMrGNkAAo1jeYsHamd0esOJv0nKU',
    appId: '1:271054827387:web:131102f5be06f4bafc57de',
    messagingSenderId: '271054827387',
    projectId: 'banalyze-d42d9',
    authDomain: 'banalyze-d42d9.firebaseapp.com',
    storageBucket: 'banalyze-d42d9.firebasestorage.app',
    measurementId: 'G-2FLCG06MBV',
  );
}
